services:
  expense-backend-app:
    build: ./Backend
    container_name: expense-backend-app
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CLIENT_URL=http://localhost:3000
      - FRONTEND_URL=http://localhost:3000
      - TRUST_PROXY=1
    networks:
      - app-network

  expense-frontend-app:
    build:
      context: ./Frontend
      args:
        - INTERNAL_API_URL=http://expense-backend-app:5000
    container_name: expense-frontend-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=http://expense-backend-app:5000
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - expense-backend-app

networks:
  app-network:
    driver: bridge